app = "bahaya" # ganti nama bebas. harus unik di fly
primary_region = "sin" # Singapore paling deket ke Binance

[build]
  builder = "paketobuildpacks/builder:base" # biar otomatis deteksi python

[env]
  TZ = "Asia/Jakarta" # biar log pake WIB

[processes]
  app = "python main.py" # <--- PENTING. Ini command buat jalanin bot

[deploy]
  release_command = "python -c \"print('Bot Starting')\"" # opsional

[[services]]
  # Bot ini gak pake web, jadi services dikosongin aja
  # Kalau ada error "no services" abaikan aja. Bot jalan di background
