app = "bahaya"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[processes]
  web = "python main.py"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256 # [UDAH 256]
