app = "bahaya"
primary_region = "sin"

[build]
dockerfile = "Dockerfile"

[env]
TZ = "Asia/Jakarta"

[processes]
app = "python main.py"

[deploy]
restart_policy = "always" # <- Crash auto nyala lagi

# HAPUS [http_service] SEMUA. GA DIPAKE

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 256 # <- INI DIGANTI JADI 256
