import asyncio
import os
import time
import requests
import hmac
import hashlib
import gc
from urllib.parse import urlencode
from datetime import datetime, timezone, timedelta

# ========== CONFIG ==========
BINANCE_API_KEY = os.getenv("API_KEY")
BINANCE_SECRET = os.getenv("API_SECRET")
SUPABASE_URL = os.getenv("SUPA_URL")
SUPABASE_KEY = os.getenv("SUPA_KEY")
TELE_TOKEN = os.getenv("TELE_TOKEN")
TELE_CHAT_ID = os.getenv("TELE_CHAT_ID")

SYMBOL = "BTCUSDT"
BASE_COIN = "BTC"
QUOTE_COIN = "USDT"
LOOP_SEC = 3
BUFFER_USDT = 0.5
TABEL = "orders" # TAMBAH INI

# ========== CONFIG ATR + GRID ==========
ATR_PERIOD = 14
ATR_TIMEFRAME = "1h"
ATR_MULTIPLIER = 0.5
GRID_MIN = 250
GRID_MAX = 1000

# ========== CONFIG MODE PEMANASAN ==========
WAIT_FIRST_BUY = 600 # 10 menit
FIRST_BUY_DONE = False
START_TIME = time.time()

# ========== GLOBAL ==========
BASE_URL = "https://api.binance.com"
BINANCE_RULES = {}
GRID_MANAGER = {"grid_step": GRID_MIN, "date": None, "atr": 0}
DAILY_STATS = {"trade_count": 0, "profit_usdt": 0.0, "date": None}
WIB = timezone(timedelta(hours=7))

SB_HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal"
}

# ========== FUNGSI SUPABASE + AUTO CREATE TABEL ==========
def sb_query(sql):
    try:
        url = f"{SUPABASE_URL}/rest/v1/rpc/exec_sql"
        headers = SB_HEADERS.copy()
        headers["Prefer"] = "params=single-object"
        r = requests.post(url, headers=headers, json={"sql": sql}, timeout=5)
        return r.status_code
    except: return 500

def auto_create_table():
    check = sb_select("orders", "select=id&limit=1")
    if isinstance(check, list):
        print("Tabel 'orders' sudah ada")
        return
    print("Tabel 'orders' tidak ada. Membuat otomatis...")
    sql = """
    create table if not exists public.orders (
      id bigint generated by default as identity primary key,
      order_id text,
      side text,
      price numeric,
      qty numeric,
      status text,
      created_at timestamp with time zone default now()
    );
    alter table public.orders disable row level security;
    """
    status = sb_query(sql)
    if status == 200:
        print("Tabel 'orders' berhasil dibuat + RLS dimatikan")
        send_telegram("✅ Tabel 'orders' di Supabase berhasil dibuat otomatis")

def sb_select(table, filters=""):
    try:
        url = f"{SUPABASE_URL}/rest/v1/{table}?{filters}"
        r = requests.get(url, headers=SB_HEADERS, timeout=5)
        return r.json() if r.status_code == 200 else []
    except Exception as e: return f"ERROR: {e}"

def sb_insert(table, data):
    try:
        url = f"{SUPABASE_URL}/rest/v1/{table}"
        requests.post(url, headers=SB_HEADERS, json=data, timeout=5)
    except Exception as e: print(f"SB INSERT ERROR: {e}")

def sb_delete(table, filters):
    try:
        url = f"{SUPABASE_URL}/rest/v1/{table}?{filters}"
        requests.delete(url, headers=SB_HEADERS, timeout=5)
    except Exception as e: print(f"SB DELETE ERROR: {e}")

# ========== FUNGSI TELEGRAM + SALDO ==========
def get_all_balance():
    data = signed_request("GET", "/api/v3/account")
    saldo_usdt = 0
    saldo_btc = 0
    for a in data['balances']:
        if a['asset'] == QUOTE_COIN: saldo_usdt = float(a['free'])
        if a['asset'] == BASE_COIN: saldo_btc = float(a['free'])
    return saldo_usdt, saldo_btc

def send_telegram(msg):
    try:
        url = f"https://api.telegram.org/bot{TELE_TOKEN}/sendMessage"
        data = {"chat_id": TELE_CHAT_ID, "text": msg, "parse_mode": "HTML"}
        requests.post(url, data=data, timeout=5)
    except Exception as e: print(f"TELEGRAM ERROR: {e}")

# ========== SATPAM BINANCE ==========
def get_binance_rules(symbol):
    global BINANCE_RULES
    r = requests.get(f"{BASE_URL}/api/v3/exchangeInfo?symbol={symbol}", timeout=5)
    info = r.json()['symbols'][0]
    for f in info['filters']:
        if f['filterType'] == 'MIN_NOTIONAL': BINANCE_RULES['min_notional'] = float(f['minNotional'])
        if f['filterType'] == 'LOT_SIZE':
            BINANCE_RULES['min_qty'] = float(f['minQty'])
            BINANCE_RULES['step_size'] = float(f['stepSize'])

def signed_request(method, path, params={}):
    params['timestamp'] = int(time.time() * 1000)
    query_string = urlencode(params)
    signature = hmac.new(BINANCE_SECRET.encode(), query_string.encode(), hashlib.sha256).hexdigest()
    headers = {'X-MBX-APIKEY': BINANCE_API_KEY}
    url = f"{BASE_URL}{path}?{query_string}&signature={signature}"
    return requests.request(method, url, headers=headers, timeout=5).json()

def get_price(): return float(requests.get(f"{BASE_URL}/api/v3/ticker/price?symbol={SYMBOL}", timeout=3).json()['price'])

# ========== KUNCI BARU: WAJIB SYNC DULU ==========
def wajib_sync_dulu():
    """KUNCI: Selalu sync Binance + Supabase sebelum action apapun"""
    print("[SYNC] Sinkronisasi 1 arah dari BINANCE...")
    sync_dan_cek(SYMBOL)
    time.sleep(1)
    print("[SYNC] Selesai. Data sudah paling update")

# ========== SYNC 1 ARAH DARI BINANCE ==========
def sync_dan_cek(symbol):
    """ATURAN: Data dari Binance = Benar. Supabase ngikutin Binance"""
    try:
        # 1. AMBIL DATA DARI BINANCE
        bin_orders = signed_request("GET", "/api/v3/openOrders", {"symbol": symbol})
        positions_binance = signed_request("GET", "/api/v3/account")

        prices_binance_buy = set()
        prices_binance_sell = set()
        for o in bin_orders:
            p = float(o['price'])
            if o['side'] == 'BUY': prices_binance_buy.add(p)
            if o['side'] == 'SELL': prices_binance_sell.add(p)

        btc_binance = 0
        for a in positions_binance['balances']:
            if a['asset'] == BASE_COIN: btc_binance = float(a['free'])

        # 2. AMBIL DATA DARI SUPABASE
        sb_orders = sb_select(TABEL, "status=eq.active")
        if isinstance(sb_orders, str): sb_orders = []
        prices_supabase = {float(d['price']) for d in sb_orders}

        # 3. ATURAN 1: SUPABASE KOSONG, BINANCE ADA -> ISI SUPABASE
        for p in prices_binance_buy:
            if p not in prices_supabase:
                print(f"[SYNC] Ditemukan BUY di Binance {p}. MENAMBAH ke Supabase...")
                sb_insert(TABEL, {"price": p, "side": "BUY", "status": "active"})
        for p in prices_binance_sell:
            if p not in prices_supabase:
                print(f"[SYNC] Ditemukan SELL di Binance {p}. MENAMBAH ke Supabase...")
                sb_insert(TABEL, {"price": p, "side": "SELL", "status": "active"})

        # 4. ATURAN 2: SUPABASE ADA, BINANCE KOSONG -> HAPUS SUPABASE
        for d in sb_orders:
            p = float(d['price'])
            side = d['side']
            if side == 'BUY' and p not in prices_binance_buy:
                print(f"[SYNC] Ada BUY {p} di Supabase tapi kosong di Binance. MENGHAPUS...")
                sb_delete(TABEL, f"price=eq.{p}&side=eq.BUY")
            if side == 'SELL' and p not in prices_binance_sell:
                print(f"[SYNC] Ada SELL {p} di Supabase tapi kosong di Binance. MENGHAPUS...")
                sb_delete(TABEL, f"price=eq.{p}&side=eq.SELL")

        print("[SYNC] Selesai. Supabase 100% ngikutin Binance")

    except Exception as e:
        print(f"[SYNC ERROR] {e}")

# ========== SUPABASE LOGIC ==========
def get_filled_buys():
    data = sb_select(TABEL, "select=price&side=eq.BUY&status=eq.active&order=price.asc")
    if isinstance(data, str): return []
    return sorted([float(d['price']) for d in data])

def delete_filled_buys_up_to(price_limit):
    sb_delete(TABEL, f"side=eq.BUY&price=lte.{price_limit}")

def is_price_exist(price):
    data = sb_select(TABEL, f"select=id&price=eq.{price}")
    if isinstance(data, str): return False
    return len(data) > 0

def cek_total_posisi(): # BUAT CEK BUY PAKSA
    data = sb_select(TABEL, "select=id&status=eq.active")
    if isinstance(data, str): return 0
    return len(data)

# ========== FEE + QTY ==========
def get_fee_rate():
    data = signed_request("GET", "/api/v3/account")
    fee = float(data['takerCommission']) / 10000
    return fee

def hitung_qty_aman(harga, target_usdt=5):
    qty = target_usdt / harga
    if qty < BINANCE_RULES['min_qty']: qty = BINANCE_RULES['min_qty']
    step = BINANCE_RULES['step_size']
    qty = round(qty / step) * step
    if qty * harga < BINANCE_RULES['min_notional']: qty += step
    return round(qty, 8)

def hitung_butuh_modal(price, qty, fee):
    return (price * qty) + (price * qty * fee * 2) + BUFFER_USDT

# ========== ATR MANAGER ==========
def get_atr(symbol, period=14, interval="1h"):
    r = requests.get(f"{BASE_URL}/api/v3/klines?symbol={symbol}&interval={interval}&limit={period+1}", timeout=5)
    data = r.json()
    tr_list = []
    for i in range(1, len(data)):
        high, low, prev_close = float(data[i][2]), float(data[i][3]), float(data[i-1][4])
        tr = max(high-low, abs(high-prev_close), abs(low-prev_close))
        tr_list.append(tr)
    return sum(tr_list[-period:]) / period

def update_grid_manager():
    global GRID_MANAGER, DAILY_STATS
    now_wib = datetime.now(WIB)
    hari_ini_wib = now_wib.strftime("%Y-%m-%d")
    if DAILY_STATS["date"]!= hari_ini_wib:
        DAILY_STATS = {"trade_count": 0, "profit_usdt": 0.0, "date": hari_ini_wib}
    if GRID_MANAGER["date"] is None: GRID_MANAGER["date"] = hari_ini_wib
    return GRID_MANAGER["grid_step"]

def generate_grid_levels(harga_tengah, grid_step):
    levels = []
    for i in range(-2, 3):
        level = round((harga_tengah + i * grid_step) / grid_step) * grid_step
        if level > 0: levels.append(level)
    return sorted(list(set(levels)))

# ========== EKSEKUSI FIX HARGA ==========
def place_order_real(side, price_grid, qty, is_reentry=False, is_instan_darurat=False):
    global DAILY_STATS
    wajib_sync_dulu() # KUNCI: SYNC DULU SEBELUM TEMBAK

    if side == "BUY" and is_price_exist(price_grid):
        print(f"SKIP BUY: Harga {price_grid} sudah ada ordernya")
        return None

    print(f"===== [REAL] TEMBAK {side} {qty} BTC di ~{price_grid} =====")
    order = signed_request("POST", "/api/v3/order", {"symbol": SYMBOL, "side": side, "type": "MARKET", "quantity": qty})

    if 'fills' in order and len(order['fills']) > 0:
        harga_isi = sum(float(f['price']) * float(f['qty']) for f in order['fills']) / sum(float(f['qty']) for f in order['fills'])
        harga_isi = round(harga_isi, 2)
    else: harga_isi = float(order.get('avgPrice', price_grid))

    sb_insert(TABEL, {"price": harga_isi, "side": side, "status": "active"})

    saldo_usdt, saldo_btc = get_all_balance()
    fee = get_fee_rate()
    butuh_modal = hitung_butuh_modal(harga_isi, qty, fee) if side == "BUY" else 0
    DAILY_STATS["trade_count"] += 1
    if side == "SELL":
        filled_buys = get_filled_buys()
        avg_buy = sum(filled_buys)/len(filled_buys) if filled_buys else harga_isi
        profit = (harga_isi * qty * (1 - fee)) - (avg_buy * qty * (1 + fee))
        DAILY_STATS["profit_usdt"] += profit
        delete_filled_buys_up_to(harga_isi) # hapus buy yg udah kejual

    emoji = "🟢" if side == "BUY" else "🔴"
    tipe = " <b>SELL INSTAN DARURAT</b>" if is_instan_darurat else " <b>RE-ENTRY GRID</b>" if is_reentry else ""
    msg = f"{emoji} <b>{side}{tipe}</b>\nSymbol: {SYMBOL}\nPrice: {harga_isi}\nQty: {qty}"
    if side == "BUY": msg += f"\n<b>Butuh Modal:</b> {butuh_modal:.2f} USDT"
    msg += f"\n\n<b>Saldo Sisa:</b>\nUSDT: {saldo_usdt:.2f}\nBTC: {saldo_btc:.6f}"
    send_telegram(msg)
    return order

# ========== LOGIKA SELL INSTAN DARURAT ==========
def cek_sell_instan_darurat(price):
    wajib_sync_dulu() # KUNCI: SYNC DULU
    filled_buys = get_filled_buys()
    _, saldo_btc = get_all_balance()
    if not filled_buys or saldo_btc == 0: return False
    buy_kelewat = [b for b in filled_buys if b <= price]
    if not buy_kelewat: return False

    harga_tertinggi_kelewat = max(buy_kelewat)
    print(f"!!! SELL INSTAN DARURAT!!! Harga: {price}")
    qty = saldo_btc
    if qty < BINANCE_RULES['min_qty']: return False
    place_order_real("SELL", price, qty, is_instan_darurat=True)
    return True

def cek_signal_sell(price):
    wajib_sync_dulu() # KUNCI: SYNC DULU
    grid_step = update_grid_manager()
    grid_levels = generate_grid_levels(price, grid_step)
    grid_atas = [g for g in grid_levels if g > price]
    if not grid_atas: return None, None, False
    target_grid = min(grid_atas)
    _, saldo_btc = get_all_balance()
    qty = hitung_qty_aman(target_grid)
    if saldo_btc < qty: return None, None, False
    ada_buy = len(sb_select(TABEL, f"price=eq.{target_grid}&side=eq.BUY&status=eq.active")) > 0
    return ("SELL", target_grid, False) if ada_buy else ("SELL", target_grid, True)

def cek_signal_buy(price):
    global FIRST_BUY_DONE
    wajib_sync_dulu() # KUNCI: SYNC DULU

    if not FIRST_BUY_DONE:
        sisa = WAIT_FIRST_BUY - (time.time() - START_TIME)
        if sisa > 0:
            print(f"[PEMANASAN] Tunggu {int(sisa)}s lagi")
            return None, None
        else:
            if cek_total_posisi() > 0: # Cek lagi abis sync
                print("[SYNC] Ternyata udah ada posisi. Skip Buy Paksa")
                FIRST_BUY_DONE = True
                return None, None
            print(f"[PEMANASAN] Selesai. BUY PAKSA PERTAMA @ {price}")
            qty = hitung_qty_aman(price)
            fee = get_fee_rate()
            butuh_usdt = hitung_butuh_modal(price, qty, fee)
            saldo_usdt, _ = get_all_balance()
            if saldo_usdt >= butuh_usdt:
                FIRST_BUY_DONE = True
                return "BUY", price
            else: return None, None

    grid_step = update_grid_manager()
    grid_levels = generate_grid_levels(price, grid_step)
    grid_bawah = [g for g in grid_levels if g < price]
    if not grid_bawah: return None, None
    target_grid = max(grid_bawah)
    if is_price_exist(target_grid): return None, None
    qty = hitung_qty_aman(target_grid)
    fee = get_fee_rate()
    butuh_usdt = hitung_butuh_modal(target_grid, qty, fee)
    saldo_usdt, _ = get_all_balance()
    if saldo_usdt >= butuh_usdt:
        return "BUY", target_grid
    else: return None, None

# ========== LOOP UTAMA ==========
async def main():
    global START_TIME
    START_TIME = time.time()
    auto_create_table()
    get_binance_rules(SYMBOL)
    update_grid_manager()
    wajib_sync_dulu() # SYNC PERTAMA KALI JALAN
    saldo_usdt, saldo_btc = get_all_balance()
    harga_sekarang = get_price()
    send_telegram(f"🤖 <b>Bot V11.17 Jalan</b>\nMode: REAL | Sync 1 Arah ON\n<b>Harga BTC:</b> {harga_sekarang}\n<b>Saldo:</b>\nUSDT: {saldo_usdt:.2f}\nBTC: {saldo_btc:.6f}")
    cek_sell_instan_darurat(harga_sekarang)
    await asyncio.sleep(3)
    print("Bot V11.17 MODE REAL. Menunggu 10 menit untuk buy pertama...")

    while True:
        try:
            price = get_price()
            signal_buy, grid_buy = cek_signal_buy(price)
            signal_sell, grid_sell, is_reentry = cek_signal_sell(price)

            if signal_sell:
                qty = hitung_qty_aman(grid_sell)
                place_order_real("SELL", grid_sell, qty, is_reentry=is_reentry)
                if is_reentry:
                    if not is_price_exist(grid_sell):
                        place_order_real("BUY", grid_sell, hitung_qty_aman(grid_sell), is_reentry=True)
            if signal_buy:
                qty = hitung_qty_aman(grid_buy)
                place_order_real("BUY", grid_buy, qty)

            gc.collect()
            await asyncio.sleep(LOOP_SEC)
        except Exception as e:
            send_telegram(f"❌ <b>ERROR BOT</b>\n{e}")
            await asyncio.sleep(5)

if __name__ == "__main__":
    asyncio.run(main())
