import asyncio
import os
import time
import requests
import hmac
import hashlib
import gc
from urllib.parse import urlencode
from datetime import datetime, timezone, timedelta

# ========== CONFIG ==========
BINANCE_API_KEY = os.getenv("API_KEY")
BINANCE_SECRET = os.getenv("API_SECRET")
SUPABASE_URL = os.getenv("SUPA_URL")
SUPABASE_KEY = os.getenv("SUPA_KEY")
TELE_TOKEN = os.getenv("TELE_TOKEN")
TELE_CHAT_ID = os.getenv("TELE_CHAT_ID")

SYMBOL = "BTCUSDT"
BASE_COIN = "BTC"
QUOTE_COIN = "USDT"
LOOP_SEC = 3
BUFFER_USDT = 0.5
TABEL = "orders"

# ========== CONFIG ATR + GRID ==========
ATR_PERIOD = 14
ATR_TIMEFRAME = "1h"
ATR_MULTIPLIER = 0.5
GRID_MIN = 250
GRID_MAX = 1000

# ========== CONFIG MODE PEMANASAN ==========
WAIT_FIRST_BUY = 10
FIRST_BUY_DONE = False
START_TIME = time.time()

# ========== GLOBAL ==========
BASE_URL = "https://api.binance.com"
BINANCE_RULES = {'min_notional': 5.0, 'min_qty': 0.00001, 'step_size': 0.00001}
GRID_MANAGER = {"grid_step": GRID_MIN, "date": None, "atr": 0}
DAILY_STATS = {"trade_count": 0, "profit_usdt": 0.0, "date": None}
WIB = timezone(timedelta(hours=7))
NOTIF_FLAGS = {"error": False, "saldo_kurang": False}

BUY_HISTORY = set()
LAST_ERROR_MSG = ""

SB_HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal"
}

def sb_query(sql):
    try:
        url = f"{SUPABASE_URL}/rest/v1/rpc/exec_sql"
        headers = SB_HEADERS.copy()
        headers["Prefer"] = "params=single-object"
        r = requests.post(url, headers=headers, json={"sql": sql}, timeout=5)
        return r.status_code
    except: return 500

def sb_select(table, filters=""):
    try:
        url = f"{SUPABASE_URL}/rest/v1/{table}?{filters}"
        r = requests.get(url, headers=SB_HEADERS, timeout=5)
        return r.json() if r.status_code == 200 else []
    except Exception as e: return []

def auto_create_table():
    check = sb_select("orders", "select=id&limit=1")
    if isinstance(check, list): print("Tabel 'orders' sudah ada"); return
    sql = "create table if not exists public.orders (id bigint generated by default as identity primary key, side text, price numeric, qty numeric, status text, created_at timestamp with time zone default now()); alter table public.orders disable row level security;"
    status = sb_query(sql)
    if status == 200: print("Tabel 'orders' berhasil dibuat"); send_telegram("✅ Tabel 'orders' di Supabase berhasil dibuat otomatis")

def sb_insert(table, data):
    try: requests.post(f"{SUPABASE_URL}/rest/v1/{table}", headers=SB_HEADERS, json=data, timeout=5)
    except Exception as e: print(f"SB INSERT ERROR: {e}")

def sb_delete(table, filters):
    try: requests.delete(f"{SUPABASE_URL}/rest/v1/{table}?{filters}", headers=SB_HEADERS, timeout=5)
    except Exception as e: print(f"SB DELETE ERROR: {e}")

def get_all_balance():
    data = signed_request("GET", "/api/v3/account")
    saldo_usdt = 0; saldo_btc = 0
    for a in data['balances']:
        if a['asset'] == QUOTE_COIN: saldo_usdt = float(a['free'])
        if a['asset'] == BASE_COIN: saldo_btc = float(a['free'])
    return saldo_usdt, saldo_btc

def send_telegram(msg):
    try:
        url = f"https://api.telegram.org/bot{TELE_TOKEN}/sendMessage"
        requests.post(url, data={"chat_id": TELE_CHAT_ID, "text": msg, "parse_mode": "HTML"}, timeout=5)
    except Exception as e: print(f"TELEGRAM ERROR: {e}")

def get_binance_rules(symbol):
    global BINANCE_RULES
    try:
        r = requests.get(f"{BASE_URL}/api/v3/exchangeInfo?symbol={symbol}", timeout=5)
        info = r.json()['symbols'][0]
        for f in info['filters']:
            if f['filterType'] == 'MIN_NOTIONAL': BINANCE_RULES['min_notional'] = float(f['minNotional'])
            if f['filterType'] == 'LOT_SIZE':
                BINANCE_RULES['min_qty'] = float(f['minQty'])
                BINANCE_RULES['step_size'] = float(f['stepSize'])
        print(f"[RULES] Update dari Binance: {BINANCE_RULES}")
    except: print(f"[RULES] Gagal. Pakai default: {BINANCE_RULES}")

def signed_request(method, path, params={}):
    params['timestamp'] = int(time.time() * 1000)
    query_string = urlencode(params)
    signature = hmac.new(BINANCE_SECRET.encode(), query_string.encode(), hashlib.sha256).hexdigest()
    headers = {'X-MBX-APIKEY': BINANCE_API_KEY}
    url = f"{BASE_URL}{path}?{query_string}&signature={signature}"
    return requests.request(method, url, headers=headers, timeout=5).json()

def get_price(): return float(requests.get(f"{BASE_URL}/api/v3/ticker/price?symbol={SYMBOL}", timeout=3).json()['price'])

def get_filled_buys():
    try:
        trades = signed_request("GET", "/api/v3/myTrades", {"symbol": SYMBOL, "limit": 500})
        buys = [float(t['price']) for t in trades if t['isBuyer']]
        return sorted(list(set(buys)))
    except: return []

def delete_filled_buys_up_to(price_limit):
    sb_delete(TABEL, f"side=eq.BUY&price=lte.{price_limit}")

def is_price_exist(price):
    trades = signed_request("GET", "/api/v3/myTrades", {"symbol": SYMBOL, "limit": 100, "startTime": int((time.time() - 300) * 1000)})
    for t in trades:
        if abs(float(t['price']) - price) < 0.5 and t['isBuyer']:
            return True
    return False

def cek_total_posisi():
    _, saldo_btc = get_all_balance()
    return saldo_btc

def get_fee_rate():
    data = signed_request("GET", "/api/v3/account")
    return float(data['takerCommission']) / 10000

def hitung_qty_aman(harga, target_usdt=5):
    qty = target_usdt / harga
    if qty < BINANCE_RULES['min_qty']: qty = BINANCE_RULES['min_qty']
    step = BINANCE_RULES['step_size']
    qty = round(qty / step) * step
    if qty * harga < BINANCE_RULES['min_notional']: qty += step
    return round(qty, 8)

def format_qty(qty):
    step = BINANCE_RULES['step_size']
    qty = round(qty / step) * step
    return ('%.8f' % qty).rstrip('0').rstrip('.')

def hitung_butuh_modal(price, qty, fee):
    return (price * qty) + (price * qty * fee * 2) + BUFFER_USDT

def get_atr(symbol, period=ATR_PERIOD, interval=ATR_TIMEFRAME):
    r = requests.get(f"{BASE_URL}/api/v3/klines?symbol={symbol}&interval={interval}&limit={period+1}", timeout=5)
    data = r.json(); tr_list = []
    for i in range(1, len(data)):
        high, low, prev_close = float(data[i][2]), float(data[i][3]), float(data[i-1][4])
        tr = max(high-low, abs(high-prev_close), abs(low-prev_close)); tr_list.append(tr)
    return sum(tr_list[-period:]) / period

def update_grid_manager():
    global GRID_MANAGER, DAILY_STATS
    now_wib = datetime.now(WIB); hari_ini_wib = now_wib.strftime("%Y-%m-%d")
    if DAILY_STATS["date"]!= hari_ini_wib: DAILY_STATS = {"trade_count": 0, "profit_usdt": 0.0, "date": hari_ini_wib}

    atr = get_atr(SYMBOL)
    grid_step = atr * ATR_MULTIPLIER
    grid_step = max(GRID_MIN, min(grid_step, GRID_MAX))
    grid_step = round(grid_step / 50) * 50

    GRID_MANAGER["grid_step"] = grid_step
    GRID_MANAGER["atr"] = atr
    GRID_MANAGER["date"] = hari_ini_wib
    print(f"[ATR] ATR: {atr:.2f} | Grid Step: {grid_step:.0f}")
    return grid_step

def generate_grid_levels(harga_tengah, grid_step):
    levels = []
    for i in range(-3, 4):
        level = round((harga_tengah + i * grid_step) / grid_step) * grid_step
        if level > 0: levels.append(level)
    return sorted(list(set(levels)))

def place_order_real(side, price_grid, qty, is_reentry=False, is_instan_darurat=False):
    global DAILY_STATS, NOTIF_FLAGS, BUY_HISTORY, LAST_ERROR_MSG

    price_key = round(price_grid, 1)

    if side == "BUY" and price_key in BUY_HISTORY:
        print(f"SKIP: Grid {price_key} sudah dibeli. Tunggu SELL dulu"); return None

    saldo_usdt, _ = get_all_balance()
    butuh_modal = hitung_butuh_modal(price_grid, qty, get_fee_rate())
    if side == "BUY" and saldo_usdt < butuh_modal:
        msg = f"⏸️ <b>PAUSE BUY</b>\nButuh: {butuh_modal:.2f} USDT\nSaldo: {saldo_usdt:.2f} USDT"
        if msg!= LAST_ERROR_MSG: send_telegram(msg); LAST_ERROR_MSG = msg
        print(msg); return None

    qty_str = format_qty(qty)
    print(f"===== [REAL] TEMBAK {side} {qty_str} BTC di ~{price_grid} =====")
    order = signed_request("POST", "/api/v3/order", {"symbol": SYMBOL, "side": side, "type": "MARKET", "quantity": qty_str})

    if 'orderId' not in order:
        error_reason = order.get('msg', 'Unknown Error')
        msg = f"❌ <b>ORDER GAGAL 1X</b>\nSide: {side}\nHarga: {price_grid}\nAlasan: {error_reason}"
        if msg!= LAST_ERROR_MSG: send_telegram(msg); LAST_ERROR_MSG = msg
        print(msg); return None

    LAST_ERROR_MSG = ""

    if 'fills' in order and len(order['fills']) > 0:
        harga_isi = sum(float(f['price']) * float(f['qty']) for f in order['fills']) / sum(float(f['qty']) for f in order['fills'])
        harga_isi = round(harga_isi, 2)
    else: harga_isi = float(order.get('avgPrice', price_grid))

    saldo_usdt, saldo_btc = get_all_balance()
    sb_insert(TABEL, {"price": harga_isi, "side": side, "status": "active"})

    fee = get_fee_rate()
    butuh_modal = hitung_butuh_modal(harga_isi, qty, fee) if side == "BUY" else 0
    DAILY_STATS["trade_count"] += 1

    if side == "BUY":
        BUY_HISTORY.add(price_key)

    if side == "SELL":
        filled_buys = get_filled_buys()
        avg_buy = sum(filled_buys)/len(filled_buys) if filled_buys else harga_isi
        profit = (harga_isi * qty * (1 - fee)) - (avg_buy * qty * (1 + fee))
        DAILY_STATS["profit_usdt"] += profit
        delete_filled_buys_up_to(harga_isi)
        BUY_HISTORY.discard(round(avg_buy, 1))

        if not is_instan_darurat and not is_reentry:
            # LANGSUNG RE-ENTRY TANPA DELAY
            if not is_price_exist(harga_isi): place_order_real("BUY", harga_isi, hitung_qty_aman(harga_isi), is_reentry=True)

    if side == "SELL" and NOTIF_FLAGS["saldo_kurang"]:
        NOTIF_FLAGS["saldo_kurang"] = False
        send_telegram("✅ <b>Saldo sudah masuk. Bot lanjut normal</b>")

    emoji = "🟢" if side == "BUY" else "🔴"; tipe = " <b>SELL INSTAN DARURAT</b>" if is_instan_darurat else " <b>RE-ENTRY GRID</b>" if is_reentry else ""
    msg = f"{emoji} <b>{side}{tipe}</b>\nSymbol: {SYMBOL}\nPrice: {harga_isi}\nQty: {qty_str}"
    if side == "BUY": msg += f"\n<b>Butuh Modal:</b> {butuh_modal:.2f} USDT"
    msg += f"\n<b>ATR:</b> {GRID_MANAGER['atr']:.2f} | <b>Grid:</b> {GRID_MANAGER['grid_step']:.0f}"
    msg += f"\n\n<b>Saldo Sisa:</b>\nUSDT: {saldo_usdt:.2f}\nBTC: {saldo_btc:.6f}"
    send_telegram(msg); return order

def cek_sell_instan_darurat(price):
    filled_buys = get_filled_buys(); _, saldo_btc = get_all_balance()
    if not filled_buys or saldo_btc == 0: return False
    buy_kelewat = [b for b in filled_buys if b <= price]
    if not buy_kelewat: return False

    print(f"!!! SELL INSTAN DARURAT!!! Harga: {price}")
    qty = saldo_btc
    if qty < BINANCE_RULES['min_qty']: return False
    place_order_real("SELL", price, qty, is_instan_darurat=True)
    # LANGSUNG RE-ENTRY TANPA DELAY
    if not is_price_exist(price): place_order_real("BUY", price, hitung_qty_aman(price), is_reentry=True)
    return True

def cek_signal_sell(price):
    grid_step = update_grid_manager(); grid_levels = generate_grid_levels(price, grid_step)
    grid_atas = [g for g in grid_levels if g > price]
    if not grid_atas: return None, None, False
    target_grid = min(grid_atas); _, saldo_btc = get_all_balance()
    qty = hitung_qty_aman(target_grid)
    if saldo_btc < qty: return None, None, False
    ada_buy = is_price_exist(target_grid)
    return ("SELL", target_grid, ada_buy)

def cek_signal_buy(price):
    global FIRST_BUY_DONE, NOTIF_FLAGS
    if not FIRST_BUY_DONE:
        sisa = WAIT_FIRST_BUY - (time.time() - START_TIME)
        if sisa > 0: print(f"[PEMANASAN] Tunggu {int(sisa)}s lagi"); return None, None
        else:
            if cek_total_posisi() > 0: print("[BINANCE] Ternyata udah ada BTC. Skip Buy Paksa"); FIRST_BUY_DONE = True; return None, None

            qty = hitung_qty_aman(price)
            fee = get_fee_rate()
            butuh_usdt = hitung_butuh_modal(price, qty, fee)
            saldo_usdt, _ = get_all_balance()

            if saldo_usdt < butuh_usdt:
                if not NOTIF_FLAGS["saldo_kurang"]:
                    send_telegram(f"⚠️ <b>SALDO KURANG</b>\nButuh: {butuh_usdt:.2f} USDT\nPunya: {saldo_usdt:.2f} USDT")
                    NOTIF_FLAGS["saldo_kurang"] = True
                return None, None

            print(f"[PEMANASAN] Selesai. BUY PAKSA PERTAMA @ {price}")
            FIRST_BUY_DONE = True
            return "BUY", price

    grid_step = update_grid_manager(); grid_levels = generate_grid_levels(price, grid_step)
    grid_bawah = [g for g in grid_levels if g < price]
    if not grid_bawah: return None, None
    target_grid = max(grid_bawah)
    if is_price_exist(target_grid): return None, None
    qty = hitung_qty_aman(target_grid); fee = get_fee_rate(); butuh_usdt = hitung_butuh_modal(target_grid, qty, fee)
    saldo_usdt, _ = get_all_balance()
    if saldo_usdt >= butuh_usdt: return "BUY", target_grid
    else: return None, None

async def main():
    global START_TIME, NOTIF_FLAGS; START_TIME = time.time()
    auto_create_table(); get_binance_rules(SYMBOL); update_grid_manager()
    saldo_usdt, saldo_btc = get_all_balance(); harga_sekarang = get_price()
    send_telegram(f"🤖 <b>Bot V11.35 ATR GRID NO DELAY</b>\n<b>Harga BTC:</b> {harga_sekarang}\n<b>Saldo:</b>\nUSDT: {saldo_usdt:.2f}\nBTC: {saldo_btc:.6f}")
    cek_sell_instan_darurat(harga_sekarang); await asyncio.sleep(3)
    print("Bot V11.35 MODE REAL. Menunggu 10 detik untuk buy pertama...")

    while True:
        try:
            price = get_price()
            signal_buy, grid_buy = cek_signal_buy(price)
            signal_sell, grid_sell, is_reentry = cek_signal_sell(price)

            if signal_sell:
                qty = hitung_qty_aman(grid_sell)
                place_order_real("SELL", grid_sell, qty, is_reentry=is_reentry)
            if signal_buy:
                qty = hitung_qty_aman(grid_buy)
                place_order_real("BUY", grid_buy, qty)

            gc.collect(); await asyncio.sleep(LOOP_SEC)
        except Exception as e:
            if not NOTIF_FLAGS["error"]:
                send_telegram(f"❌ <b>ERROR BOT</b>\n{e}")
                NOTIF_FLAGS["error"] = True
            print(f"ERROR: {e}")
            await asyncio.sleep(5)
            NOTIF_FLAGS["error"] = False

if __name__ == "__main__":
    asyncio.run(main())
